---
title: "sensitivity, specificity, positive and negative predictive values of combined
  tests"
output:
  pdf_document
---

Define X: {not infected, infected} $\rightarrow$ {0, 1} by X(not infected) = 0 and X(infected) = 1.\
Define T a sample space that describes the sequence of two tests for which $T_1$ is the first test (Test 1) and $T_2$ is the second test (Test 2). Then we have $T_1, T_2$: {negative, positive}$\rightarrow$ {0, 1} by $T_1, T_2$(negative) = 0 and $T_1, T_2$(positive) = 1.\
Define sensitivity $p=P(T=1|X=1)$\
Define specificity $q=P(T=0|X=0)$\
Let $p_1, q_1$ denote the sensitivity and specificity of Test 1.\
Let $p_2, q_2$ denote the sensitivity and specificity of Test 2.\
Let $p_T, q_T$ denote the sensitivity and specificity of the combined tests.\
Let $\pi$ denotes the prevalence.\
Assume that there is no change of infection status throughout the period we consider and also assume that results of individual tests $T_1, T_2$ are independent.\
Overall, we have considered 3 different scenarios as follows.

# Section 1: Calculating sensitivity and specificity of combined tests

## Scenario 1
If Test 1 is positive, define T as positive. If Test 1 is negative, repeat Test 2 after 3 days. If Test 2 is positive, define T as positive. Otherwise T is negative.\
In this scenario,\
$P(T_1=1|X=1)=p_1$, $P(T_1=0|X=0)=q_1$\
$P(T_2=1|X=1)=p_2$, $P(T_2=0|X=0)=q_2$\
By definition, the sensitivity of combined tests in this case is
\begin{align*}
p_T &= P(T\ positive| X=1)\\
&= 1-P(T\ negative|X=1)\\
&=1-P(T_1=0,T_2=0|X=1)\\
&=1-P(T_1=0|X=1)P(T_2=0|X=1)(since\ the\ result\ of\ T_1,T_2\ are\ independent)\\
&=1-(1-p_1)(1-p_2)\\
&=p_1+p_2(1-p_1)
\end{align*}
And the specificity of combined test in this case is
\begin{align*}
q_T &= P(T\ negative|X=0)\\
&=P(T_1=0,T_2=0|X=0)\\
&=P(T_1=0|X=0)P(T_2=0|X=0)\ (since\ the\ result\ of\ T_1,T_2\ are\ independent)\\
&=q_1q_2
\end{align*}
Note that if Test 1 and Test 2 are the same kind of tests,\
$P(T_1=1|X=1)=P(T_2=1|X=1)=p_1$\
$P(T_1=0|X=0)=P(T_2=0|X=0)=q_1$\
Therefore, simply replace $p_2,q_2$ with $p_1,q_1$ respectively\
We have the sensitivity of combined tests in this case is
\begin{align*}
p_T = 2p_1-p_1^2
\end{align*}
And the specificity of combined test in this case is
\begin{align*}
q_T =q_1^2
\end{align*}

## Scenario 2
If Test 1 is negative, T is negative. If Test 1 is positive, repeat after three days. If Test 2 is negative, T is negative, otherwise T is positive.\
Note that in this scenario, Test 1 must be the golden standard PCR test. Since it has the general high performance in sensitivity than other kinds of tests, only then we can define this scenario as if the first test is negative, the result if negative.\
If Test 1 and Test 2 are different tests, we have
$P(T_1=1|X=1)=p_1$, $P(T_1=0|X=0)=q_1$\
$P(T_2=1|X=1)=p_2$, $P(T_2=0|X=0)=q_2$\
The sensitivity of combined tests in this case is
\begin{align*}
p_T &= P(T\ positive| X=1)\\
&= P(T_1 = 1, T_2 = 1|X=1)\\
&= P(T_1=1|X=1)P(T_2=1|X=1)\ (since\ the\ result\ of\ T_1,T_2\ are\ independent)\\
&=p_1p_2
\end{align*}
And the specificity of combined test in this case is
\begin{align*}
q_T &= P(T\ negative|X=0)\\
&=1-P(T\ positive|X=0)\\
&=1-P(T_1=1,T_2=1|X=0)\\
&=1-P(T_1=1|X=0)P(T_2=1|X=0)(since\ the\ result\ of\ T_1,T_2\ are\ independent)\\
&=1-(1-q_1)(1-q_2)\\
&=q_1+q_2(1-q_1)
\end{align*}
If Test 1 and Test 2 are the same kind of tests,simply replace $p_2,q_2$ with $p_1,q_1$ respectively\
$P(T_1=1|X=1)=P(T_2=1|X=1)=p_1$\
$P(T_1=0|X=0)=P(T_2=0|X=0)=q_1$\
The sensitivity of combined tests in this case is
\begin{align*}
p_T = p_1^2
\end{align*}
And the specificity of combined test in this case is
\begin{align*}
q_T = 2q_1-q_1^2
\end{align*}

# Section 2: Calculating positive and negative predictive values of both individual and combined test

## Individual tests:
By definition, positive predictive values (PPV) is given the test result is positive, what is the probability that the person has the disease.
\begin{align*}
PPV &= P(X=1|T=1)\\
&=\frac{P(X=1)P(T=1|X=1)}{P(T=1)}\\
&=\frac{P(X=1)P(T=1|X=1)}{P(X=0)P(T=1|X=0)+P(X=1)P(T=1|X=1)}(By\ Law\ of\ Total\ Probability)\\
&= \frac{\pi p}{\pi p+(1-\pi)(1-q)}
\end{align*}
By definition, negative predictive values (NPV) is given the test result is negative, what is the probability that the person does not have the disease.
\begin{align*}
NPV &= P(X=0|T=0)\\
&= \frac{P(X=0)P(T=0|X=0)}{P(T=0)}\\
&=\frac{P(X=0)P(T=0|X=0)}{P(X=0)P(T=0|X=0)+P(X=1)P(T=0|X=1)}(By\ Law\ of\ Total\ Probability)\\
&=\frac{(1-\pi)q}{(1-\pi)q+\pi(1-p)}
\end{align*}

## Combined tests:

### Scenario 1(same as above)
By Law of Total Probability, we have\
$P(T_1=0)=P(X=0)P(T_1=0|X=0)+P(X=1)P(T_1=0|X=1)\\= (1-\pi)q_1+\pi(1-p_1)$\
$P(T_1=1)=P(X=0)P(T_1=1|X=0)+P(X=1)P(T_1=1|X=1)\\=(1-\pi)(1-q_1)+\pi p_1$\
$P(T_2=0)=P(X=0)P(T_2=0|X=0)+P(X=1)P(T_2=0|X=1)\\= (1-\pi)q_2+\pi(1-p_2)$\
$P(T_2=1)=P(X=0)P(T_2=1|X=0)+P(X=1)P(T_2=1|X=1)\\=(1-\pi)(1-q_2)+\pi p_2$\
The positive predictive values for combined test is
\begin{align*}
PPV_T &= P(X=1|T\ is\ positive)\\
&=P(X=1|T_1=1 \ Or \ T_1=0,T_2=1)\\
&=\frac{P(X=1\cap T_1=1)+P(X=1\cap T_1=0,T_2=1)}{P(T_1=1)+P(T_1=0,T_2=1)}(event\  T_1=0,\ T_1=1\ form \ a\ partition\ of\ sample\ space)\\
&=\frac{P(T_1=1)P(X=1|T_1=1)+P(T_1=0,T_2=1)P(X=1|T_1=0,T_2=1)}{P(T_1=1)+P(T_1=0,T_2=1)}(by\ Bayesian\ Theorem)\\
&=\frac{P(X=1)P(T_1=1|X=1)+P(X=1)P(T_1=0,T_2=1|X=1)}{P(T_1=1)+P(T_1=0)P(T_2=1)}(by\ Conditional\ Probability)\\
&=\frac{\pi p_1+\pi p_2(1-p_1)}{(1-\pi)(1-q_1)+\pi p_1+((1-\pi)q_1+\pi(1-p_1))((1-\pi)(1-q_2)+\pi p_2)}
\end{align*}
The negative predictive values for combined test is
\begin{align*}
(*)NPV_T &=P(X=0|T\ is\ negative)\\
&=P(X=0|T_1=0,T_2=0)\\
&=\frac{P(X=0)P(T_1=0,T_2=0|X=0)}{P(T_1=0,T_2=0)}(by\ Bayesian\ Theorem)\\
&=\frac{P(X=0)P(T_1=0|X=0)P(T_2=0|X=0)}{P(T_1=0)P(T_2=0)}(by\ Conditional\ Probability)\\
&=\frac{(1-\pi)q_1q_2}{((1-\pi)q_1+\pi(1-p_1))((1-\pi)q_2+\pi(1-p_2))}
\end{align*}
Note that if Test 1 and Test 2 are the same kind of tests,\
$P(T_1=0)=P(T_2=0)= P(X=0)P(T_1=0|X=0)+P(X=1)P(T_1=0|X=1)\\= (1-\pi)q_1+\pi(1-p_1)$\
$P(T_1=1)=P(T_2=1)=P(X=0)P(T_1=1|X=0)+P(X=1)P(T_1=1|X=1)\\=(1-\pi)(1-q_1)+\pi p_1$\
in this scenario.\
By simply replacing $P(T_2=1)$ and $P(T_2=0)$ with $P(T_1=1)$ and $P(T_1=0)$ and $p_2,q_2$ with $p_1,q_1$ respectively, we have the positive predictive values for combined test is
\begin{align*}
PPV_T =\frac{\pi p_1(2-p_1)}{((1-\pi)(1-q_1)+\pi p_1)((1-\pi)q_1+\pi(1-p_1)+1)}
\end{align*}
And the negative predictive values for combined test is
\begin{align*}
(*)NPV_T=\frac{(1-\pi)q_1^2}{((1-\pi)q_1+\pi(1-p_1))^2}
\end{align*}

### Scenario 2(same as above)
By Law of Total Probability, we have\
$P(T_1=0)=P(X=0)P(T_1=0|X=0)+P(X=1)P(T_1=0|X=1)\\= (1-\pi)q_1+\pi(1-p_1)$\
$P(T_1=1)=P(X=0)P(T_1=1|X=0)+P(X=1)P(T_1=1|X=1)\\=(1-\pi)(1-q_1)+\pi p_1$\
$P(T_2=0)=P(X=0)P(T_2=0|X=0)+P(X=1)P(T_2=0|X=1)\\= (1-\pi)q_2+\pi(1-p_2)$\
$P(T_2=1)=P(X=0)P(T_2=1|X=0)+P(X=1)P(T_2=1|X=1)\\=(1-\pi)(1-q_2)+\pi p_2$\
The positive predictive values for combined test is
\begin{align*}
(*)PPV_T &=P(X=1|T\ is\ positive)\\ &=P(X=1|T_1=1,T_2=1)\\
&=\frac{P(X=1)P(T_1=1,T_2=1|X=1)}{P(T_1=1,T_2=1)}(by\ Bayesian\ Theorem)\\
&=\frac{P(X=1)P(T_1=1|X=1)P(T_2=1|X=1)}{P(T_1=1)P(T_2=1)}(by\ Conditional\ Probability)\\
&=\frac{\pi p_1p_2}{((1-\pi)(1-q_1)+\pi p_1)((1-\pi)(1-q_2)+\pi p_2)}
\end{align*}
And the negative predictive values for combined test is
\begin{align*}
NPV_T &=P(X=0|T\ is\ negative)\\
&=P(X=0|T_1=0\ Or\ T_1=1,T_2=0)\\
&=\frac{P(X=0\cap T_1=0)+P(X=0\cap T_1=1,T_2=0)}{P(T_1=0)+P(T_1=1,T_2=0)}(event\  T_1=0,\ T_1=1\ form \ a\ partition\ of\ sample\ space)\\
&=\frac{P(T_1=0)P(X=0|T_1=0)+P(T_1=1,T_2=0)P(X=0|T_1=1,T_2=0)}{P(T_1=0)+P(T_1=1,T_2=0)}(by\ Bayesian\ Theorem)\\
&=\frac{P(X=0)P(T_1=0|X=0)+P(X=0)P(T_1=1,T_2=0|X=0)}{P(T_1=0)+P(T_1=1)P(T_2=0)}(by\ Conditional\ Probability)\\
&=\frac{(1-\pi)(q_1+q_2-q_1q_2)}{(1-\pi)q_1+\pi(1-p_1)+((1-\pi)(1-q_1)+\pi p_1)((1-\pi)q_2+\pi(1-p_2))}
\end{align*}
Note that if Test 1 and Test 2 are the same kind of tests,\
$P(T_1=0)=P(T_2=0)= P(X=0)P(T_1=0|X=0)+P(X=1)P(T_1=0|X=1)\\= (1-\pi)q_2+\pi(1-p_2)$\
$P(T_1=1)=P(T_2=1)=P(X=0)P(T_1=1|X=0)+P(X=1)P(T_1=1|X=1)\\=(1-\pi)(1-q_2)+\pi p_2$\
in this scenario.\
By simply replacing $P(T_2=1)$ and $P(T_2=0)$ with $P(T_1=1)$ and $P(T_1=0)$ and $p_2,q_2$ with $p_1,q_1$ respectively, we have the positive predictive values for combined test is
\begin{align*}
(*)PPV_T=\frac{\pi p_1^2}{((1-\pi)(1-q_1)+\pi p_1)^2}
\end{align*}
The negative predictive values for combined test is
\begin{align*}
NPV_T=\frac{1-\pi q_1(2-q_1)}{((1-\pi)q_1+\pi(1-p_1))((1-\pi)(1-q_1)+\pi p_1+1)}
\end{align*}
