---
title: "combined test v2"
output:
  pdf_document: default
---

Define X: {not infected, infected} $\rightarrow$ {0, 1} by X(not infected) = 0 and X(infected) = 1.\
Define T a sample space that describes the sequence of two tests for which $T_1$ is the first test (Test 1) and $T_2$ is the second test (Test 2). Then we have $T_1, T_2$: {negative, positive}$\rightarrow$ {0, 1} by $T_1, T_2$(negative) = 0 and $T_1, T_2$(positive) = 1.\
Define sensitivity $p=P(T=1|X=1)$\
Define specificity $q=P(T=0|X=0)$\
Let $p_1, q_1$ denote the sensitivity and specificity of Test 1.\
Let $p_2, q_2$ denote the sensitivity and specificity of Test 2.\
Let $p_T, q_T$ denote the sensitivity and specificity of the combined tests.\
Let $\pi$ denotes the prevalence.\
Assume that there is no change of infection status throughout the period we consider.\


# Section 1: Calculating sensitivity and specificity of combined tests

## Believe the Positive:

We have $P(T_1=1|X=1)=p_1$, $P(T_1=0|X=0)=q_1$, $P(T_2=1|X=1)=p_2$, $P(T_2=0|X=0)=q_2$ by definition.\
Therefore, the overall sensitivity of combined tests is
\begin{align*}
p_T &= P(T\ positive| X=1)\\
&= 1-P(T\ negative|X=1)\\
&=1-P(T_1=0,T_2=0|X=1)\\
&=1-P(T_2=0|T_1=0,X=1)P(T_1=0|X=1)
\end{align*}
We do not know how to simplify $P(T_2=0|T_1=0,X=1)$.\
However, we can assume that if $T_1$ and $T_2$ are independent, then $P(T_2=0|T_1=0,X=1)=P(T_2=0|X=1)$. \
In the case that the two tests are not independent, we can define a dependent variable "\textbf{a}" such that
\begin{center}
$P(T_2=0|T_1=0,X=1)=aP(T_2=0|X=1) \in [0,1]$
\end{center}
Therefore,
\begin{align*}
p_T &=1-P(T_2=0|T_1=0,X=1)P(T_1=0|X=1)\\
&= 1-aP(T_2=0|X=1)P(T_1=0|X=1)\\
&= 1-a(1-p_1)(1-p_2)
\end{align*}

We also need\ $p_T=1-a(1-p_1)(1-p_2)\in [0,1]$ \
And the overall specificity of combined test is
\begin{align*}
q_T &= P(T\ negative|X=0)\\
&=P(T_1=0,T_2=0|X=0)\\
&=P(T_2=0|T_1=0,X=0)P(T_1=0|X=0)
\end{align*}
Similar as above, we can define a dependent variable "\textbf{b}" such that 
\begin{center}
$P(T_2=0|T_1=0,X=0)=bP(T_2=0|X=0) \in [0,1]$
\end{center}
Therefore,
\begin{align*}
q_T &=P(T_2=0|T_1=0,X=0)P(T_1=0|X=0)\\
&= bP(T_2=0|X=0)P(T_1=0|X=0)\\
&= bq_1q_2
\end{align*}

We also need\ $q_T=bq_1q_2\in [0,1]$\
Note that if Test 1 and Test 2 are independent,\
$P(T_2=0|T_1=0,X=1)=P(T_2=0|X=1)=1-p_2$\
$P(T_2=0|T_1=0,X=0)=P(T_2=0|X=0)=q_2$\
We have the overall sensitivity of combined tests is
\begin{align*}
p_T = 1-(1-p_1)(1-p_2)
\end{align*}
And the overall specificity of combined test is
\begin{align*}
q_T =q_1q_2
\end{align*}

## Believe the Negative:

By carrying out the similar calculation as for the BP case, we have the following results:
The overall sensitivity of combined tests is
\begin{align*}
p_T &= P(T\ positive| X=1)\\
&=ap_1p_2
\end{align*}
We also need\ $p_T=ap_1p_2 \in[0,1]$\
And the overall specificity of combined test is
\begin{align*}
q_T &= P(T\ negative|X=0)\\
&=1-b(1-q_1)(1-q_2)
\end{align*}
We also need\ $q_T=1-b(1-q_1)(1-q_2) \in[0,1]$\
The overall sensitivity of combined tests is
\begin{align*}
p_T = p_1p_2
\end{align*}
And the overall specificity of combined test is
\begin{align*}
q_T = 1-(1-q_1)(1-q_2)
\end{align*}


If Test 1 and Test 2 are different tests, we have
$P(T_1=1|X=1)=p_1$, $P(T_1=0|X=0)=q_1$\
$P(T_2=1|X=1)=p_2$, $P(T_2=0|X=0)=q_2$\
The overall sensitivity of combined tests is
\begin{align*}
p_T &= P(T\ positive| X=1)\\
&= P(T_1 = 1, T_2 = 1|X=1)\\
&= P(T_2=1|T_1=1,X=1)P(T_1=1|X=1)\\
&= aP(T_2=1|X=1)P(T_1=1|X=1)\ (using\ dependent\ variable\ a\ defined\ above)\\
&=ap_1p_2
\end{align*}
And the overall specificity of combined test is
\begin{align*}
q_T &= P(T\ negative|X=0)\\
&=1-P(T\ positive|X=0)\\
&=1-P(T_1=1,T_2=1|X=0)\\
&=1-P(T_2=1|T_1=1,X=0)P(T_1=1|X=0)\\
&=1-bP(T_2=1|X=0)P(T_1=1|X=0)\ (using\ dependent\ variable\ b\ defined\ above)\\
&=1-b(1-q_1)(1-q_2)
\end{align*}
Note that if Test 1 and Test 2 are independent,\
$P(T_2=1|T_1=1,X=1)=P(T_2=1|X=1)=p_2$\
$P(T_2=1|T_1=1,X=0)=P(T_2=1|X=0)=1-q_2$\
We have the overall sensitivity of combined tests is
\begin{align*}
p_T = p_1p_2
\end{align*}
And the overall specificity of combined test is
\begin{align*}
q_T = 1-(1-q_1)(1-q_2)
\end{align*}

# Section 2: Calculating positive and negative predictive values of both individual and combined test

## Individual tests:
By definition, positive predictive values (PPV) is
\begin{align*}
PPV &= P(X=1|T=1)\\
&=\frac{P(X=1)P(T=1|X=1)}{P(T=1)}\\
&=\frac{P(X=1)P(T=1|X=1)}{P(X=0)P(T=1|X=0)+P(X=1)P(T=1|X=1)}(By\ Law\ of\ Total\ Probability)\\
&= \frac{\pi p}{\pi p+(1-\pi)(1-q)}
\end{align*}
By carrying similar calculations above, negative predictive values (NPV) is
\begin{align*}
NPV &= P(X=0|T=0)\\
&=\frac{(1-\pi)q}{(1-\pi)q+\pi(1-p)}
\end{align*}

## Combined tests:

Calculating the combined positive and negative predictive by inserting the corresponding combined sensitivity and specificity into the formula of positive and negative predictive value in the individual case.

### Believe the Positive:

The positive predictive values for combined test is
\begin{align*}
PPV_T &= \frac{\pi (1-a(1-p_1)(1-p_2))}{\pi (1-a(1-p_1)(1-p_2))+(1-\pi)(1-bq_1q_2)}
\end{align*}
And the negative predictive values for combined test is
\begin{align*}
NPV_T &= \frac{(1-\pi)bq_1q_2}{(1-\pi)bq_1q_2+\pi a(1-p_1)(1-p_2)}
\end{align*}
Note that if Test 1 and Test 2 are independent,\
The positive predictive values for combined test is
\begin{align*}
PPV_T &= \frac{\pi (p_1+p_2(1-p_1))}{\pi (p_1+p_2(1-p_1))+(1-\pi)(1-q_1q_2)}
\end{align*}
And the negative predictive values for combined test is
\begin{align*}
NPV_T &= \frac{(1-\pi)q_1q_2}{(1-\pi)q_1q_2+\pi(1-p_1)(1-p_2)}
\end{align*}
Note that if Test 1 and Test 2 are the same kind of tests,simply replacing $p_2,q_2$ with $p_1,q_1$ respectively, we have the positive predictive values for combined test is\
\begin{align*}
PPV_T &= \frac{\pi(2p_1-p_1^2)}{\pi (2p_1-p_1^2)+(1-\pi)(1-q_1^2)}
\end{align*}
The negative predictive values for combined test is
\begin{align*}
NPV_T &= \frac{(1-\pi)q_1^2}{(1-\pi)q_1^2+\pi(1-2p_1+p_1^2)}
\end{align*}

### Believe the Negative:
The positive predictive values for combined test is
\begin{align*}
PPV_T &= \frac{\pi ap_1p_2}{\pi ap_1p_2+b(1-\pi)(1-q_1)(1-q_2)}
\end{align*}
And the negative predictive values for combined test is
\begin{align*}
NPV_T &= \frac{(1-\pi)(1-b(1-q_1)(1-q_2))}{(1-\pi)(1-b(1-q_1)(1-q_2))+\pi(1-ap_1p_2)}
\end{align*}
Note that if Test 1 and Test 2 are independent,\
The positive predictive values for combined test is
\begin{align*}
PPV_T &= \frac{\pi p_1p_2}{\pi p_1p_2+(1-\pi)(1-q_1)(1-q_2)}
\end{align*}
And the negative predictive values for combined test is
\begin{align*}
NPV_T &= \frac{(1-\pi)(q_1+q_2(1-q_1))}{(1-\pi)(q_1+q_2(1-q_1))+\pi(1-p_1p_2)}
\end{align*}
Note that if Test 1 and Test 2 are the same kind of tests,simply replacing $p_2,q_2$ with $p_1,q_1$ respectively, we have the positive predictive values for combined test is\
\begin{align*}
PPV_T &= \frac{\pi p_1^2}{\pi p_1^2+(1-\pi)(1-2q_1+q_1^2)}
\end{align*}
The negative predictive values for combined test is
\begin{align*}
NPV_T &= \frac{(1-\pi)(2q_1-q_1^2)}{(1-\pi)(2q_1-q_1^2)+\pi(1-p_1^2)}
\end{align*}